Insert into question(qid, text) values
	(1, "Do you have a headache?"),
	(2, "Are you reporting a headache you had?"),
	(3, "Are you reporting a medication you took?"),
	(4, "Have a wonderful day!"),
    (5, "What name do you give this headache?"),
    (6, "Did you wake up with this headache?"),
    (7, "What is/was the duration of your headache?"),
    (8, "How severe is your headache?"),
    (9, "Was it a USC facility?"),
    (10, "Thank you for recording your headache. You may always review and edit your current or previous response."),
    (11, "How many times has it happened since you wokeup?"),
    (12, "For this headache, did you take medication?"),
    (13, "Did you have to go to a physician for this headache?"),
    (14, "What medication was it?"),
    (15, "If female, are you in the middle or close to your menstruction cycle?"),
    (16, "Did you experience another form of headache?"),
    (17, "How severe was your headache prior to medication?"),
    (18, "Did this medication help your headache?"),
    (19, "How many pills?");
    
    
Insert into leadsTo(parentQID, childQID, response) values
	(1, 5, "Yes"),
    (1, 2, "No"),
    (2, 5, "Yes"),
    (2, 3, "No"),
    (3, 14, "Yes"),
    (3, 4, "No"),
    (5, 6, "Name"),
    (6, 7, "Yes"),
    (6, 7, "No"),
    (7, 8, "Duration"),
    (8, 11, "Duration"),
    (9, 10, "Response"),
    (11, 12, "Count"),
    (12, 14, "Yes"),
    (12, 16, "No"),
    (13, 9, "Yes"),
    (13, 10, "No"),
    (14, 19, "Response"),
    (15, 13, "Response"),
    (16, 5, "Yes"),
    (16, 15, "No"),
    (17, 16, "Response"),
    (18, 17, "Yes"),
    (18, 16, "No"),
    (19, 18, "Response");
    